### ISSUE TITLE
Plans to upgrade to Guzzle 5?

### ISSUE THREAD

**Issue by nathanielks** [uecode/segment-io-php#3]
Hey all!

Any plans on upgrading to Guzzle 5?

**Comment by kmfk** [comment]
@nathanielks - not at the moment, but will in the future. 

While I've been using this library successfully on guzzle 4 with the current command & service libraries, I'm dragging my feet while @mtdowling works on getting those libs to a stable release - then I'll get to updating.

Anything pressing that the library doesn't do for you now?

**Comment by nathanielks** [comment]
@kmfk it _works_ just fine! Thanks for sharing this with the world! When I was running unit tests there's an obscure exception thrown in guzzle/guzzle-services. I believe the test case is whenever the Segment API expects certain parameters and doesn't receive them. The guzzle exception class expects 2 parameters, but second isn't the type it's expecting: https://github.com/guzzle/guzzle-services/issues/47. The error message specifically is:

```
'ErrorException' with message 'Argument 2 passed to GuzzleHttp\Command\Exception\CommandException::__construct() must be an instance of GuzzleHttp\Command\CommandTransaction, instance of GuzzleHttp\Command\Guzzle\GuzzleClient given
```

IRC, with the release of Guzzle 5, there isn't any intermediate versions of guzzle-services that fix the bug _and_ can be used with Guzzle 4. I was in a rush and don't remember testing guzzle-services 0.4. Le sigh...

**Comment by nathanielks** [comment]
To be more specific ( after having done research ), guzzle-services 0.4 required guzzle/command 0.7, which is for Guzzle 5.

**Comment by kmfk** [comment]
@nathanielks - out of curiosity, what was the test that caused the exception? Is there an easy way to reproduce it?

There will be an inevitable move to guzzle 5, but in the meantime, I wonder if its possible to better handle that exception in this client until we make the move.

**Comment by nathanielks** [comment]
@kmfk IIRC, the exception is thrown when a bogus or empty write key is provided and it can't communicate with Segment.

**Comment by kmfk** [comment]
@nathanielks - sorry for the delay.  Was hoping to see a major version on guzzle/command and guzzle/guzzle-services, but didn't feel like waiting any longer.

https://github.com/uecode/segment-io-php/releases/tag/1.1.0
