### ISSUE TITLE
Sending events without attached properties not possible

### ISSUE THREAD

**Issue by alexleutgoeb** [uecode/segment-io-php#4]
First of all, thanks for sharing that library! I found a possible issue during sending events without any properties attached, I'm however not sure if that's arising from your code or from guzzle itself:

I'm tried sending events the following way:

1:

```php
$client->track([
  'userId'=> '1',
  'event' => 'Test Event'
  ])
```

and

```php
$client->track([
  'userId'=> '1',
  'event' => 'Test Event',
  'properties' => null
  ])
```

results in a PHP error, I guess that's cause the properties parameter is defined as 'required' in the guzzle description file.

2:

```php
$client->track([
  'userId'=> '1',
  'event' => 'Test Event',
  'properties' => []
  ])
```
results in `Array ( [success] => 1 [batched] => 1 )`, the event is however never delivered to Segment.

Is sending events without attached properties supported by your library, anyhow? If not, any plans to fix that?

Many thanks!

**Comment by kmfk** [comment]
@alexleutgoeb - I ran through a bunch of tests here and it seems like its actually only the segment end - they still return a success message on these.  

To check it, I actually disabled the `required` constraint on 'properties' and used the Debug subscriber to dump out the requests and responses.

Not much I can do here.
